language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - composer install --dev --no-interaction

script:
  - ./phpunit.sh

after_script:
  # - php vendor/bin/coveralls
  # or enable logging
  - php vendor/bin/coveralls -v
